### ISSUE TITLE
Rules Tracker

### ISSUE THREAD

**Issue by RedRelay** [RedRelay/SpongeCreeperHeal#4]
* [x] <span style="color:green;">minecraft:stone_pressure_plate : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBasePressurePlate></span>
* [x] <span style="color:green;">minecraft:birch_door : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockDoor></span>
* [x] <span style="color:green;">minecraft:potatoes : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockCrops></span>
* [x] <span style="color:green;">minecraft:yellow_flower : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:ladder : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockLadder></span>
* [x] <span style="color:green;">minecraft:jungle_door : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockDoor></span>
* [x] <span style="color:green;">minecraft:redstone_wire : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRedstoneWire></span>
* [x] <span style="color:green;">minecraft:rail : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRailBase></span>
* [x] <span style="color:green;">minecraft:nether_wart : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:activator_rail : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRailBase></span>
* [x] <span style="color:green;">minecraft:red_mushroom : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:cocoa : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockCocoa></span>
* [x] <span style="color:green;">minecraft:chorus_flower : fr.redrelay.spongecreeperheal.engine.dependency.rule.ChorusFlowerDependencyRule<net.minecraft.block.BlockChorusFlower></span>
* [x] <span style="color:green;">minecraft:unlit_redstone_torch : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockTorch></span>
* [x] <span style="color:green;">minecraft:sand : fr.redrelay.spongecreeperheal.engine.dependency.rule.GravityAffectedDependencyRule</span>
* [x] <span style="color:green;">minecraft:beetroots : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockCrops></span>
* [x] <span style="color:green;">minecraft:redstone_torch : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockTorch></span>
* [x] <span style="color:green;">minecraft:wall_banner : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockBanner$BlockBannerHanging></span>
* [x] <span style="color:green;">minecraft:sapling : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:stone_button : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockButton></span>
* [x] <span style="color:green;">minecraft:lever : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockLever></span>
* [x] <span style="color:green;">minecraft:flower_pot : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockFlowerPot></span>
* [x] <span style="color:green;">minecraft:carrots : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockCrops></span>
* [x] <span style="color:green;">minecraft:fire : fr.redrelay.spongecreeperheal.engine.dependency.rule.FireDependencyRule<net.minecraft.block.BlockFire></span>
* [x] <span style="color:green;">minecraft:standing_banner : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBanner$BlockBannerStanding></span>
* [x] <span style="color:green;">minecraft:tripwire_hook : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockTripWireHook></span>
* [x] <span style="color:green;">minecraft:red_flower : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:anvil : fr.redrelay.spongecreeperheal.engine.dependency.rule.GravityAffectedDependencyRule</span>
* [x] <span style="color:green;">minecraft:golden_rail : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRailBase></span>
* [x] <span style="color:green;">minecraft:unpowered_repeater : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRedstoneDiode></span>
* [x] <span style="color:green;">minecraft:double_plant : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:wooden_door : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockDoor></span>
* [x] <span style="color:green;">minecraft:concrete_powder : fr.redrelay.spongecreeperheal.engine.dependency.rule.GravityAffectedDependencyRule</span>
* [x] <span style="color:green;">minecraft:gravel : fr.redrelay.spongecreeperheal.engine.dependency.rule.GravityAffectedDependencyRule</span>
* [x] <span style="color:green;">minecraft:snow_layer : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockSnow></span>
* [x] <span style="color:green;">minecraft:wooden_pressure_plate : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBasePressurePlate></span>
* [x] <span style="color:green;">minecraft:pumpkin_stem : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:chorus_plant : fr.redrelay.spongecreeperheal.engine.dependency.rule.ChorusPlantDependencyRule<net.minecraft.block.BlockChorusPlant></span>
* [x] <span style="color:green;">minecraft:wooden_button : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockButton></span>
* [x] <span style="color:green;">minecraft:wall_sign : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockWallSign></span>
* [x] <span style="color:green;">minecraft:vine : fr.redrelay.spongecreeperheal.engine.dependency.rule.VineDependencyRule<net.minecraft.block.BlockVine></span>
* [x] <span style="color:green;">minecraft:cactus : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockCactus></span>
* [x] <span style="color:green;">minecraft:brown_mushroom : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:powered_comparator : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRedstoneDiode></span>
* [x] <span style="color:green;">minecraft:tallgrass : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:reeds : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockReed></span>
* [x] <span style="color:green;">minecraft:acacia_door : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockDoor></span>
* [x] <span style="color:green;">minecraft:melon_stem : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:spruce_door : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockDoor></span>
* [x] <span style="color:green;">minecraft:cake : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockCake></span>
* [x] <span style="color:green;">minecraft:carpet : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockCarpet></span>
* [x] <span style="color:green;">minecraft:light_weighted_pressure_plate : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBasePressurePlate></span>
* [x] <span style="color:green;">minecraft:torch : fr.redrelay.spongecreeperheal.engine.dependency.rule.DirectionalDependencyRule<net.minecraft.block.BlockTorch></span>
* [x] <span style="color:green;">minecraft:detector_rail : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRailBase></span>
* [x] <span style="color:green;">minecraft:unpowered_comparator : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRedstoneDiode></span>
* [x] <span style="color:green;">minecraft:powered_repeater : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockRedstoneDiode></span>
* [x] <span style="color:green;">minecraft:deadbush : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:standing_sign : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockStandingSign></span>
* [x] <span style="color:green;">minecraft:wheat : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockCrops></span>
* [x] <span style="color:green;">minecraft:dark_oak_door : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockDoor></span>
* [x] <span style="color:green;">minecraft:waterlily : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBush></span>
* [x] <span style="color:green;">minecraft:iron_door : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockDoor></span>
* [x] <span style="color:green;">minecraft:heavy_weighted_pressure_plate : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockBasePressurePlate></span>
* [x] <span style="color:orange;">minecraft:dragon_egg : fr.redrelay.spongecreeperheal.engine.dependency.rule.DownLayedDependencyRule<net.minecraft.block.BlockDragonEgg></span>
